# Generated by Django 4.0.4 on 2022-05-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Brief_summary',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
