# Generated by Django 4.0.4 on 2022-05-18 09:27

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('price', models.FloatField(max_length=5)),
                ('Brief_summary', models.CharField(max_length=200)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL')], max_length=3)),
                ('descripion', models.TextField(max_length=800)),
                ('Weight', models.FloatField(max_length=4)),
                ('Dimensions', models.CharField(max_length=18)),
                ('Materials', models.FloatField(max_length=2)),
                ('puplish_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to=shop.models.upload_img)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
