# Generated by Django 4.0.4 on 2022-05-20 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_clothe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Your_review', models.TextField(max_length=700)),
                ('creat_at', models.DateField(auto_now=True)),
                ('clothe_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_review', to='shop.clothe')),
            ],
        ),
    ]
