# Generated by Django 4.0.4 on 2022-05-20 08:49

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='image2',
            field=models.ImageField(default='', upload_to=shop.models.upload_img),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothe',
            name='image3',
            field=models.ImageField(default='', upload_to=shop.models.upload_img),
            preserve_default=False,
        ),
    ]
