# Generated by Django 4.0.4 on 2022-06-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_clothe_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sm', 'sm'), ('md', 'md'), ('lg', 'lg')], max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='size',
        ),
        migrations.AddField(
            model_name='clothe',
            name='size',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
