# Generated by Django 4.0.4 on 2022-06-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_size_remove_clothe_size_clothe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
