# Generated by Django 4.0.4 on 2022-06-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='size',
            field=models.ManyToManyField(related_name='sizes', to='shop.size'),
        ),
    ]
