# Generated by Django 4.0.4 on 2022-06-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_clothe_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothe',
            name='size',
        ),
        migrations.AddField(
            model_name='clothe',
            name='sizes',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
