# Generated by Django 4.0.4 on 2022-06-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
