# Generated by Django 4.0.4 on 2022-06-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='Materials_name',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
    ]
