# Generated by Django 4.0.4 on 2022-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_clothe_materials_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothe',
            name='Materials_name',
            field=models.CharField(choices=[('Chiffon', 'Chiffon'), ('Cotton', 'Cotton'), ('Crepe', 'Crepe'), ('Denim', 'Denim'), ('Lace', 'Lace'), ('Leather', 'Leather'), ('Linen', 'Linen'), ('Satin', 'Satin'), ('Silk', 'Silk'), ('Synthetics', 'Synthetics'), ('Wool', 'Wool')], max_length=20),
        ),
    ]
